### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:4304

### ISSUE THREAD

**Issue by clickworkorange** [njh/node-red-contrib-owfs#17]
I have owfs running with a default configuration, only changed to remove dummy devices and configure it for I2C. From a command promt as the Node-RED user (`su - nodrered` in my case), I can execute `owdir` and get the root directory listing: 

```
nodered@system: $ owdir -s localhost:4304 
/bus.0 
/uncached 
/settings 
/system 
/statistics 
/structure
```

Yet when I place a node-red-contrib-owfs node in my flow it says `Error: connect ECONNREFUSED 127.0.0.1:4304` in the configuration window. Curiously `owdir -s 127.0.0.1:4304` returns nothing. What might be the reason for this?

**Comment by clickworkorange** [comment]
Ok, two things: first, I needed to change the `server =` line at the very bottom of the config file (under "OWSERVER" to
```
server: port = 127.0.0.1:4304
```
Secondly, the correct command to restart the owserver is `systemctl restart owserver`, and not just `systemctl restart owfs`. Sorted! Though I don't understand why `127.0.0.1` and `localhost` behave differently; I thought these were basically interchangeable, with `localhost` being preferable since it would actually perform a look-up of the local machine's loopback IP. But what do I know :)

**Comment by njh** [comment]
Hi,

I have experienced problems like this in the past, but I wasn't sure if it was just my setup. I should probably add something to the README.

The problem is almost certainly because owserver was (only) binding to IPv6 localhost (address ::1). I would expect when using 'localhost:4304', then it should bind to both IPv4 and IPv6 localhost. Or when binding just to the port, then it should bind to that port on all interfaces.

The extra confusion is that often when connecting to a server using `owget -s foo:4304`, if it fails to connect, then there is no error message.

nick.
