### ISSUE TITLE
HIH4000

### ISSUE THREAD

**Issue by johras** [njh/node-red-contrib-owfs#4]
Not possible to select path /address/HIH4000/humidity in UI.

**Comment by njh** [comment]
Do you have any further details?
What device(s) are you testing with?

Are other devices/paths working?

**Comment by johras** [comment]
The chip is DS2438 Battery monitor with Honeywell HIH4000 sensor attached to it.
OWFS has HIH4000 folder for this chip and that folder contains the humidity field.

Node-red-contrib-owfs shows only the device's first level folders or fields and this humidity field is therefore unable to select in Node RED UI. However it works when editing manually Node RED settings file and adding this path.

# owdir /26.9266F7000000/HIH4000
/26.9266F7000000/HIH4000/humidity

# owread /26.9266F7000000/HIH4000/humidity
     55.3012

**Comment by erspearson** [comment]
I had similar UI problem with a Hobby Boards solar module
owserver exposes the Lux level at
/26.2AC8F1000000/S3-R1-A/illuminance

I don't think the problem is device specific but that the UI is making an assumption about the depth of the leaf-nodes in the hierarchy.

**Comment by njh** [comment]
Yes, the problem was the my code was assuming two levels of hierarchy, when performing the directory listing with owfs.

Fixing it was harder than I anticipated. But I then code this gist working:
https://gist.github.com/njh/4165368a7d5206c5401f5e9f1de9a0b1

And I imported that code into this module in 86b70dad357aaac88d2f83ed88bb120f8d08a57d.

Can you please test that it works for you?

**Comment by njh** [comment]
Closing due to no response.
